stanze = {}

CATEGORIE = {
    "Animali": [
        ("Leone", "Tigre"),
        ("Giraffa", "Cammello"),
        ("Panda", "Orso Polare"),
        ("Tigre", "Leopardo"),
        ("Elefante", "Rinoceronte"),
        ("Canguro", "Koala"),
        ("Lupo", "Volpe"),
        ("Pinguino", "Foca"),
        ("Delfino", "Squalo"),
        ("Aquila", "Falco"),
        ("Gatto", "Lince"),
        ("Cane", "Lupo"),
        ("Ippopotamo", "Rinoceronte"),
        ("Cobra", "Vipera"),
        ("Corvo", "Gazza Ladra"),
        ("Formica", "Termite"),
        ("Cavallo", "Zebra"),
        ("Gufo", "Civetta"),
        ("Orso", "Tasso"),
        ("Squalo", "Barracuda")
    ],
    "Oggetti": [
        ("Telefono", "Tablet"),
        ("Orologio", "Bracciale"),
        ("Zaino", "Borsa"),
        ("Sedia", "Poltrona"),
        ("Computer", "Tablet"),
        ("Lampada", "Torcia"),
        ("Chitarra", "Violino"),
        ("Bicicletta", "Monopattino"),
        ("Forbici", "Coltello"),
        ("Microonde", "Forno"),
        ("Mouse", "Touchpad"),
        ("Tastiera", "Pianoforte"),
        ("Cuffie", "Auricolari"),
        ("Bicchiere", "Tazza"),
        ("Telecomando", "Joystick"),
        ("Specchio", "Vetro"),
        ("Cuscino", "Piumone"),
        ("Bottiglia", "Caraffa"),
        ("Martello", "Mazza"),
        ("Cacciavite", "Chiave Inglese")
    ],
    "Cibi": [
        ("Pizza", "Calzone"),
        ("Pasta", "Riso"),
        ("Gelato", "Sorbetto"),
        ("Hamburger", "Hot Dog"),
        ("Sushi", "Onigiri"),
        ("Lasagna", "Cannelloni"),
        ("Torta", "Muffin"),
        ("Insalata", "Verdure Grigliate"),
        ("Patatine", "Chips"),
        ("Frittata", "Omelette"),
        ("Cioccolato", "Nutella"),
        ("Kebab", "Gyros"),
        ("Bistecca", "Filetto"),
        ("Mozzarella", "Burrata"),
        ("Caffè", "Espresso"),
        ("Vino", "Spumante"),
        ("Whiskey", "Cognac"),
        ("Brioche", "Cornetto"),
        ("Tonno", "Salmone"),
        ("Yogurt", "Budino")
    ],
    "Sport": [
        ("Calcio", "Rugby"),
        ("Basket", "Pallavolo"),
        ("Tennis", "Ping Pong"),
        ("Nuoto", "Pallanuoto"),
        ("Sci", "Snowboard"),
        ("Golf", "Mini Golf"),
        ("Boxe", "MMA"),
        ("Motociclismo", "Automobilismo"),
        ("Pallavolo", "Pallamano"),
        ("Atletica", "Maratona"),
        ("Surf", "Windsurf"),
        ("Ciclismo", "BMX"),
        ("Equitazione", "Polo"),
        ("Tiro con l’arco", "Balestra"),
        ("Karate", "Judo"),
        ("Snooker", "Biliardo"),
        ("Freccette", "Bowling"),
        ("Scherma", "Kendo"),
        ("Skateboard", "Longboard"),
        ("Paracadutismo", "Bungee Jumping")
    ],
    "Film": [
        ("Titanic", "Avatar"),
        ("Inception", "Interstellar"),
        ("Matrix", "Blade Runner"),
        ("Jurassic Park", "King Kong"),
        ("Star Wars", "Star Trek"),
        ("Pulp Fiction", "Il Padrino"),
        ("Forrest Gump", "Rain Man"),
        ("The Shining", "It"),
        ("Fight Club", "American Psycho"),
        ("The Dark Knight", "Joker"),
        ("Harry Potter", "Il Signore degli Anelli"),
        ("Frozen", "Rapunzel"),
        ("Shrek", "Madagascar"),
        ("Il Gladiatore", "Troy"),
        ("The Avengers", "Justice League"),
        ("Kill Bill", "John Wick"),
        ("C'era una volta in America", "The Irishman"),
        ("The Truman Show", "Black Mirror"),
        ("La La Land", "Moulin Rouge"),
        ("Bohemian Rhapsody", "Rocketman"),
        ("Il Re Leone", "Bambi"),
        ("Toy Story", "Coco"),
        ("Frozen", "Rapunzel"),
        ("La città incantata", "Il Castello Errante di Howl"),
        ("Akira", "Perfect Blue"),
        ("L'era glaciale", "Alla ricerca di Nemo"),
        ("Inside Out", "Soul"),
        ("Wall-E", "Up"),
        ("Kung Fu Panda", "Dragon Trainer"),
    ],
    "Personaggi di Finzione": [
        ("Batman", "Superman"),
        ("Sherlock Holmes", "Poirot"),
        ("Harry Potter", "Gandalf"),
        ("Darth Vader", "Kylo Ren"),
        ("Spiderman", "Deadpool"),
        ("Topolino", "Paperino"),
        ("Homer Simpson", "Peter Griffin"),
        ("Indiana Jones", "Lara Croft"),
        ("Dracula", "Frankenstein"),
        ("Freddy Krueger", "Saw l'enigmista"),
        ("Wolverine", "Hulk"),
        ("James Bond", "Ethan Hunt"),
        ("Goku", "Vegeta"),
        ("Naruto", "Sasuke"),
        ("Rick Sanchez", "Bender"),
        ("Capitan America", "Iron Man"),
        ("Thanos", "Dottor Destino"),
        ("Joker", "Pennywise"),
        ("Geralt di Rivia", "Legolas"),
        ("Zorro", "Robin Hood")
    ],
    "Luoghi": [
        ("Roma", "Napoli"),
        ("New York", "Los Angeles"),
        ("Tokyo", "Seoul"),
        ("Parigi", "Londra"),
        ("Sydney", "Melbourne"),
        ("Pechino", "Shanghai"),
        ("Rio de Janeiro", "Buenos Aires"),
        ("Dubai", "Doha"),
        ("Berlino", "Amsterdam"),
        ("Venezia", "Firenze"),
        ("Hawaii", "Bali"),
        ("Antartide", "Groenlandia"),
        ("Sahara", "Gobi"),
        ("Everest", "Kilimangiaro"),
        ("Grand Canyon", "Niagara Falls"),
        ("Giappone", "Corea del Sud"),
        ("Brasile", "Argentina"),
        ("Sicilia", "Sardegna"),
        ("Ibiza", "Mykonos"),
        ("Las Vegas", "Macau")
    ],
    "Volgare & Hot 🔥😈": [
        ("Velina", "Playgirl"),
        ("Vibratore", "Dildo"),
        ("Troia", "Zoccola"),
        ("Stripper", "Escort"),
        ("Scopata", "Petting"),
        ("Orgasmo", "Squirting"),
        ("69", "Missionario"),
        ("Nudista", "Esibizionista"),
        ("Sadomaso", "BDSM"),
        ("Pompino", "Leccata di passera"),
        ("Triplo Penetration", "Gang Bang"),
        ("Seno", "Tette"),
        ("Culo", "Chiappe"),
        ("Vagina", "Figa"),
        ("Sesso anale", "Doppia Penetrazione"),
        ("Shemale", "Trans"),
        ("Camgirl", "OnlyFans"),
        ("Masturbazione", "Dito in culo"),
        ("Pene", "Cazzo"),
        ("Latex", "Catwoman")
    ]
}


EMOJIS = [
    "🕵️", "🕶️", "🧐", "👻", "🎭", "😎", "🦹", "🥷", "🤖", "👀", "🦸", "👺", "🐱‍👤", "🐲", "🐸", "🐍", "🐒", "🎭",
    "🦉", "🦡", "🦦", "🦘", "🦨", "🦩", "🦚", "🦜", "🦢", "🐉", "🐺", "🐙", "🐠", "🦈", "🐬", "🐲", "🦏", "🐘", "🦛",
    "🤡", "🎃", "🦹‍♂️", "🦹‍♀️", "🦸‍♂️", "🦸‍♀️", "😈", "👾", "💀", "👽", "👑", "👁️", "🦄", "🐧", "🐼", "🐨", "🦔"
]

SOPRANNOMI = [
    "se c’è da rubare, è già lì",
    "venderebbe sua madre per 5 euro (e lo ha fatto)",
    "ha più truffe aperte di un call center nigeriano",
    "l’unico che riesce a perdere soldi a rubare",
    "ha più condanne di un dittatore africano",
    "se fosse più falso, sarebbe un orgasmo femminile",
    "campione mondiale di fuga dalle responsabilità",
    "più tossico di un gruppo Telegram di incel",
    "ruberebbe pure i fiori a un funerale",
    "quello che ti chiede un favore e sparisce",
    "ladro di cuore… e di carte di credito",
    "ha più bugie in canna di una escort sposata",
    "campione olimpico di farla franca",
    "sa cambiare più facce di una camgirl in live",
    "il peggior errore dei suoi genitori (dopo il fratello)",
    "potrebbe corrompere un prete con due birre",
    "se c'è un errore genetico, è lui",
    "la sua fedeltà dura meno di un’erezione a pagamento",
    "sembra innocente, ma ha più amanti di Rocco Siffredi",
    "mentirebbe sul nome della madre per una birra gratis",
    "il motivo per cui il papà è andato a comprare le sigarette",
    "truffatore di vecchie sole e di MILF facili",
    "ladro di baci… e di portafogli",
    "ha venduto l’anima per il Wi-Fi gratis",
    "la moralità gli fa schifo più dei preliminari",
    "se gli offri una botta, accetta anche se sei suo cugino",
    "troppo stronzo per stare simpatico, ma ci prova lo stesso",
    "ha più scheletri nell’armadio di un serial killer",
    "farebbe sesso con un cactus per 10 euro",
    "ha fregato più soldi di una chiesa evangelica",
    "se c’è da fregare qualcuno, lui ha già fatto il bonifico",
    "mentirebbe su un test di paternità per sport",
    "si fa le ex degli amici per principio",
    "ha più mogli nascoste di un emiro arabo",
    "potrebbe vendere ghiaccio agli eschimesi e scappare coi soldi",
    "farebbe un porno solo per non pagare l’affitto",
    "se c'è da sparare una cazzata, è già in mira",
    "campione mondiale di ghosting e fregature",
    "venderebbe il suo culo, ma a caro prezzo",
    "noto per scappare prima di pagare il taxi… e il figlio",
    "fa più danni di un vibratore senza batterie",
    "la sua coscienza è in ferie da quando è nato",
    "quando dice 'ti amo', sta già fregando qualcun altro",
    "venderebbe sua sorella per una ricarica Vodafone",
    "vive a scrocco come una suocera in vacanza",
    "se fosse più stronzo, lo scagionerebbero per eccesso di bastardaggine",
    "ha più debiti di un casinò in bancarotta",
    "se ti dice 'fidati', nascondi il portafogli e le figlie",
    "se c'è un colpevole, ha un alibi migliore",
    "se ti giura amore eterno, cambia casa",
    "più bugiardo di un uomo sposato in trasferta",
    "ha lasciato più ragazze incinte che i film di Rocco Siffredi",
    "la sua firma è già su troppi assegni scoperti",
    "se vedi il suo nome su un contratto, è truffa",
    "ha più ex che rimorsi, e nessuno dei due gli interessa",
    "sembra onesto, ma ha più lati oscuri di un porno giapponese",
    "potrebbe insegnare all’FBI come sparire nel nulla",
    "ha fregato così tante donne che Tinder gli ha dato il ban a vita",
    "se c'è una figa, lui è già lì (e l’ha già rovinata)",
    "più paraculo di un oroscopo personalizzato",
    "la sua promessa di fedeltà è una barzelletta in 12 lingue",
    "ha più nomi falsi di un agente sotto copertura",
    "sembra un amico, ma ha già il coltello pronto",
    "ha più doppie vite di un browser in incognito",
    "se lo vedi con la tua ragazza, è già tardi",
    "potrebbe convincerti che tua madre è adottata",
    "se c'è un prete, gli confessa una bugia per allenamento",
    "più ambiguo di un messaggio alle 3 di notte",
    "se gli presti soldi, è come regalarli alla mafia",
    "ha più segreti di un’avvocatessa divorzista",
    "se c'è un bar, è già ubriaco e senza portafoglio",
    "ha più cazzate in bocca di un televenditore di pentole",
    "nato per mentire, cresciuto per imbrogliare",
    "può venderti la sabbia del Sahara come spiaggia privata",
    "se dice che è gay, sta solo cercando di farsi tua sorella"
]



# Mappa per associare gli utenti alle loro sessioni di Socket.IO
client_sessions = {}

DEBUG = True